package com.susu.hh.mygreendao.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.susu.hh.mygreendao.entity.Student;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT".
*/
public class StudentDao extends AbstractDao<Student, Long> {

    public static final String TABLENAME = "STUDENT";

    /**
     * Properties of entity Student.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property StuId = new Property(1, Long.class, "stuId", true, "_id");
        public final static Property Tall = new Property(2, String.class, "tall", false, "TALL");
        public final static Property Age = new Property(3, String.class, "age", false, "AGE");
    };


    public StudentDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT\" (" + //
                "\"NAME\" TEXT NOT NULL ," + // 0: name
                "\"_id\" INTEGER PRIMARY KEY ," + // 1: stuId
                "\"TALL\" TEXT NOT NULL ," + // 2: tall
                "\"AGE\" TEXT NOT NULL );"); // 3: age
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
 
        Long stuId = entity.getStuId();
        if (stuId != null) {
            stmt.bindLong(2, stuId);
        }
        stmt.bindString(3, entity.getTall());
        stmt.bindString(4, entity.getAge());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Student entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
 
        Long stuId = entity.getStuId();
        if (stuId != null) {
            stmt.bindLong(2, stuId);
        }
        stmt.bindString(3, entity.getTall());
        stmt.bindString(4, entity.getAge());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public Student readEntity(Cursor cursor, int offset) {
        Student entity = new Student( //
            cursor.getString(offset + 0), // name
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // stuId
            cursor.getString(offset + 2), // tall
            cursor.getString(offset + 3) // age
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Student entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setStuId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setTall(cursor.getString(offset + 2));
        entity.setAge(cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Student entity, long rowId) {
        entity.setStuId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Student entity) {
        if(entity != null) {
            return entity.getStuId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
